### ISSUE TITLE
Ошибка при запуске без zeplin-checkpoint.txt

### ISSUE THREAD

**Issue by alexgadai** [mikeozornin/zeplin-and-figma-files-review#1]
Скрипт zeplin-download-screens.py выдаёт ошибку при попытке открыть несуществующий файл zeplin-checkpoint.txt. Проблема в функции get_checkpoint(), которая не проверяет наличие файла перед его открытием.

**Comment by alexgadai** [comment]
фикс в пулл реквесте #2

**Comment by mikeozornin** [comment]
Спасибо и здесь :–)
